all:
	g++ salao.cpp --std=c++11 -g -o salao
	g++ salao2.cpp --std=c++11 -g -o salao2
	g++ banco.cpp --std=c++11 -g -o banco
	g++ hospital.cpp --std=c++11 -g -o hospital

clean:
	rm salao salao2 banco hospital *~ -rf
